---
- name: Deploy common server configurations
  hosts: all
  become: True
  remote_user: root
  tasks:
    - include_role:
        name: common
      tags:
        - common
        - packages
        - cloudinit
        - ssh
        - sol
        - sudo
        - autoupdate
        - hostfile
        - timezone
        - users
