---
- name: Populate service facts
  ansible.builtin.service_facts: {}
  register: services_discovered

- name: List services
  ansible.builtin.debug:
    var: services_discovered

- name: Enable/Disable autoupdate services
  ansible.builtin.service:
    name: "{{ item }}"
    state: "{{ 'started' if enable_autoupdate else 'stopped' }}"
    enabled: "{{ true if enable_autoupdate else false }}"
  loop: "{{ autoupdate_services }}"
  when:
    - autoupdate_services is defined
    - item in services_discovered|flatten|list
