---
- name: "Common :: enable/disable Autoupdate Services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ autoupdate_services }}"
  when:
    - autoupdate_services is defined
    - enable_autoupdate|default(false)
