---
- name: "Common :: Disable Autoupdate Services"
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ autoupdate_services }}"
  when:
    - autoupdate_services is defined
