---

- name: "Common :: Disable Autoupdate Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ autoupdate_services }}"
  when:
    - autoupdate_services is defined
