---
- name: Configure Selinux and firewall rules for Cockpit [RedHat/CentOS]
  when: ansible_os_family == "RedHat"

  block:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: "{{ common_selinux_state }}"
    - name: Configure Firewalld allowed ports
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ common_cockpit_allowed_ports }}"
- name: Install cockpit packages
  ansible.builtin.package:
    name: "{{ common_cockpit_pkgs }}"
    state: present

- name: Enable and start cockpit service
  ansible.builtin.service:
    name: "{{ common_cockpit_service }}"
    state: started
    enabled: true
