
- name: "Configure Selinux and firewall rules for Cockpit [RedHat/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: "{{ common_selinux_state }}"
    - name: Configure Firewalld allowed ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ common_cockpit_allowed_ports }}"
  when: ansible_os_family == "RedHat"


- name: Install cockpit packages
  package:
    name: "{{ common_cockpit_pkgs }}"
    state: present
    update_cache: yes

- name: Enable and start cockpit service
  service:
    name: "{{ common_cockpit_service }}"
    state: started
    enabled: True
