---
- name: copyfiles | Remove files
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop: "{{ common_rm_files | default([]) }}"
  loop_control:
    label: "{{ item.path }} {{ item.owner }} {{ item.group }} {{ item.mode }}"
  tags:
    - rmfiles

- name: copyfiles | Create directory paths from file dest
  ansible.builtin.file:
    state: directory
    mode: "{{ item.mode | default('0774') }}"
  args: "{{ item }}"
  loop: "{{ common_directories | default([]) }}"
  loop_control:
    label: "{{ item.path }} {{ item.owner }} {{ item.group }} {{ item.mode }}"
  tags:
    - mkdirs

- name: copyfiles | Create files with provided content
  ansible.builtin.copy:
    mode: "{{ item.mode | default('0755') }}"
  args: "{{ item }}"
  loop: "{{ common_config_files | default([]) }}"
  loop_control:
    label: "{{ item.dest }} {{ item.owner }} {{ item.group }} {{ item.mode }}"
  tags:
    - mkfiles
