- name: Install cron package
  ansible.builtin.package:
    name: "{{ 'cron' if ansible_os_family == 'Debian' else 'crontabs' if ansible_os_family == 'RedHat' }}"
    state: present
  tags:
    - cronjobs
  when: ansible_os_family in ['Debian', 'RedHat']
  register: cron_package_result
  until: cron_package_result is succeeded
  changed_when: cron_package_result is changed

- name: Ensure cron service is running
  ansible.builtin.service:
    name: "{{ 'cron' if ansible_os_family == 'Debian' else 'crond' if ansible_os_family == 'RedHat' }}"
    state: started
    enabled: true
  tags:
    - cronjobs
  when: ansible_os_family in ['Debian', 'RedHat']
  register: cron_service_result
  until: cron_service_result is succeeded
  changed_when: cron_service_result is changed

- name: Create cron job
  ansible.builtin.cron:
  args: "{{ item }}"
  loop: "{{ common_cronjobs | default([]) }}"
  tags:
    - cronjobs
  when:
    - common_cronjobs | default(None) is not none
    - common_cronjobs | length > 0
  register: cronjob_result
  until: cronjob_result is succeeded
  changed_when: cronjob_result is changed
