- name: grub linux
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_CMDLINE_LINUX=.*' 
    line: 'GRUB_CMDLINE_LINUX="console={{ serialtty }},115200 console={{ consoletty }}"'
  register: update_grub

- name: grub terminal
  lineinfile: 
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_TERMINAL=.*'
    line: 'GRUB_TERMINAL="serial"'
  register: update_grub

- name: grub serial command
  lineinfile: 
    dest: /etc/default/grub
    state: present
    line: 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"'
  register: update_grub

- name: update grub
  shell: grub-mkconfig -o /boot/grub/grub.cfg
  when: update_grub.changed
