---
- name: fix root ssh login
  ansible.builtin.replace:
    path: /root/.ssh/authorized_keys
    regexp: '^.*((?=ssh-rsa))'
    replace: '\1'
    backup: yes

- name: fix root ssh login
  ansible.builtin.replace:
    path: /root/.ssh/authorized_keys
    regexp: '^no-port-forwarding.*$'
    backup: yes
