---
- name: Fix root ssh login
  ansible.builtin.replace:
    path: /root/.ssh/authorized_keys
    regexp: ^.*((?=ssh-rsa))
    replace: \1
    backup: true
- name: Fix root ssh login
  ansible.builtin.replace:
    path: /root/.ssh/authorized_keys
    regexp: ^no-port-forwarding.*$
    backup: true
