---
- name: grub-config | Include tasks to determine serial console
  ansible.builtin.include_tasks:
    file: serial-console.yml

- name: grub-config | Update /etc/default/grub lines
  tags:
    - grub-config
  block:
    - name: grub-config | Update Grub lines
      ansible.builtin.lineinfile:
        state: present
        path: /etc/default/grub
      args: "{{ item }}"
      loop: "{{ common_grub_configs }}"
      notify: Update Grub

    - name: grub-config | Copy serial-getty systemd file
      ansible.builtin.copy:
        src: "{{ common_systemd_serial_getty_src }}"
        dest: "{{ common_systemd_serial_getty_dest }}"
        remote_src: true
        group: root
        owner: root
        mode: "0755"

- name: grub-config | Flush handlers
  ansible.builtin.meta: flush_handlers
