- name: gather facts from ceph servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['mons'] | default([])}}"
  run_once: True
  tags:
    - always
- name: gather facts from ldap servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['ldap'] | default([]) }}"
  run_once: True
  tags:
    - always
- name: "Gather facts for all NFS Servers"
  setup:
    gather_subset:
      - network
  delegate_to: "{{ item }}"
  delegate_facts: True
  run_once: true
  loop: "{{ groups['nfsservers'] | default([])}}"

- name: Generate /etc/hosts template
  template:
    src: hostfile.j2
    dest: /etc/hosts
    mode: 0755
    owner: root
    group: root

