- name: "Gather facts for all ceph nodes"
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['ceph'] }}"
  when:
    - ansible_lsb.id != "Raspbian"
    - shared_storage
    - storage_backend == "cephfs"

- name: "Gather facts for all NFS Servers"
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['nfsservers'] }}"
  when:
    - shared_storage
    - storage_backend == "nfs"

- name: Generate /etc/hosts template
  template:
    src: hostfile.j2
    dest: /etc/hosts
    mode: 0755
    owner: root
    group: root
