- name: "Gather facts for all ceph nodes"
  setup:
    gather_subset:
      - network
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['ceph'] }}"
  when:
    - ansible_lsb.id != "Raspbian"
    - shared_storage is defined and shared_storage
    - storage_backend is defined and storage_backend == "cephfs"
    - hostvars[item]['ansible_default_ipv4'] is not defined

- name: "Gather facts for all NFS Servers"
  setup:
    gather_subset:
      - network
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['nfsservers'] }}"
  when:
    - shared_storage is defined and shared_storage
    - storage_backend is defined and storage_backend == "nfs"
    - hostvars[item]['ansible_default_ipv4'] is not defined

- name: Generate /etc/hosts template
  template:
    src: hostfile.j2
    dest: /etc/hosts
    mode: 0755
    owner: root
    group: root
