- name: gather facts from ceph servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['mons'] }}"
  run_once: True
  tags:
    - always

- name: "Gather facts for all NFS Servers"
  setup:
    gather_subset:
      - network
  delegate_to: "{{ item }}"
  delegate_facts: True
  run_once: true
  loop: "{{ groups['nfsservers'] }}"
  when:
    - shared_storage is defined and shared_storage
    - storage_backend is defined and storage_backend == "nfs"
    - hostvars[item]['ansible_default_ipv4'] is not defined

- name: Generate /etc/hosts template
  template:
    src: hostfile.j2
    dest: /etc/hosts
    mode: 0755
    owner: root
    group: root

