---
- name: "Common :: Load OS-Family specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Install common system packages and python dependencies"
  include_tasks:
    file: packages.yml
    apply:
      tags:
        - common
        - packages
  tags:
    - packages
    - common

- name: "Configure SSHd and root user"
  include_tasks:
    file: ssh.yml
    apply:
      tags:
        - common
        - ssh
  tags:
    - common
    - ssh

- name: "Configure /etc/hosts"
  include_tasks:
    file: hostfile.yml
    apply:
      tags:
        - common
        - hostfile
  tags:
    - common
    - hostfile

- name: "Configure system autoupdate parameters"
  include_tasks:
    file: autoupdate.yml
    apply:
      tags:
        - common
        - autoupdate
  tags:
    - common
    - autoupdate

- name: "Remove cloud-init packages and config files"
  include_tasks:
    file: cloud_init.yml
    apply:
      tags:
        - common
        - cloudinit
  tags:
    - cloudinit
    - common

- name: "Configure Sudoers"
  include_tasks:
    file: sudo.yml
    apply:
      tags:
        - common
        - sudo
  tags:
    - sudo
    - common

- name: "Check for Grub"
  stat:
    path: /boot/grub
  register: has_grub
  tags:
    - common
    - sol

- name: "Check for Grub2"
  stat:
    path: /boot/grub2
  register: has_grub2
  tags:
    - common
    - sol

- name: "Configure Serial-over-LAN [Debian]"
  include_tasks:
    file: debian-sol.yml
    apply:
      tags:
        - common
        - sol
  when: (has_grub.stat.exists or has_grub2.stat.exists) and  ansible_os_family == "Debian"
  tags:
    - common
    - sol

- name: "Configure Serial-over-LAN [RedHat]"
  include_tasks:
    file: redhat-sol.yml
    apply:
      tags:
        - common
        - sol
  when: (has_grub.stat.exists or has_grub2.stat.exists) and  ansible_os_family == "RedHat"
  tags:
    - common
    - sol

- name: "Configure Timezone Info"
  timezone:
    name: "{{ timezone }}"
  tags:
    - common
    - timezone
