- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always

- name: Set SELinux State (RHEL)
  ansible.posix.selinux:
    state: "{{ common_selinux_state }}"
  when:
    - ansible_os_family == "RedHat"

- name: "Configure SSHd and root user"
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - common-sshd

- name: "Configure Local Users and Groups"
  ansible.builtin.import_tasks: users.yml
  when: not openldap_client_enable | default(false)
  tags:
    - common-users

- name: "Configure Sudoers"
  ansible.builtin.import_tasks: sudo.yml
  tags:
    - common-sudoers

- name: "Configure /etc/hosts"
  ansible.builtin.import_tasks: hostfile.yml
  tags:
    - common-hostfile

- name: "Configure Timezone Info"
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - common-timezone

- name: "Configure system autoupdate parameters"
  ansible.builtin.import_tasks: autoupdate.yml
  tags:
    - common-autoupdate

- name: "Install common system packages and python dependencies"
  ansible.builtin.import_tasks: packages.yml
  tags:
    - common-packages

- name: "Install qemu-guest-agent on KVM hosts"
  ansible.builtin.import_tasks: qemu_guest_agent.yml
  when:
    - ansible_virtualization_role == "guest"
    - '"kvm" in ansible_virtualization_tech_guest'
  tags:
    - qemu-guest-agent

- name: "Configure Serial-over-LAN [Ubuntu]"
  ansible.builtin.import_tasks: ubuntu-sol.yml
  when:
    - ansible_os_family == "Debian"
    - ansible_virtualization_role != "guest"
    - serialtty != None
    - consoletty != None
  tags:
    - common-sol

- name: "Configure Serial-over-LAN [RHEL/CentOS]"
  ansible.builtin.import_tasks: redhat-sol.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_virtualization_role != "guest"
    - serialtty != None
    - consoletty != None
  tags:
    - common-sol

- name: "Configure MDNS reflection / Avahi"
  ansible.builtin.import_tasks: mdns_reflection.yml
  when:
    - enable_mdns_reflection | default(False)
  tags:
    - common-mdns

- name: "Install Cockpit"
  ansible.builtin.import_tasks: cockpit.yml
  tags:
    - common-cockpit
  when: common_enable_cockpit|default(False)

- name: "Reboot host if grub config was updated"
  ansible.builtin.reboot:
  when: grub_require_rebuild | default(false)
  tags:
    - common-sol
