---
- name: "Common :: Load OS-Family specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Install common system packages and python dependencies"
  include_tasks:
    file: packages.yml
    apply:
      tags:
        - common
        - packages
  tags:
    - packages
    - common

- name: "Common :: Configure SSHd and root user"
  include_tasks: ssh.yml
  tags: ssh

- name: "Configure /etc/hosts"
  include_tasks: hostfile.yml
  tags: hostfile

- name: "Common :: Configure system autoupdate parameters"
  include_tasks: autoupdate.yml

- name: "Common :: Configure Sudoers"
  include_tasks: sudo.yml
  tags: sudo

- name: "Check for Grub"
  stat:
    path: /boot/grub
  register: has_grub

- name: "Check for Grub2"
  stat:
    path: /boot/grub2
  register: has_grub2

- name: "Common :: Configure Serial-over-LAN [Debian]"
  include_tasks: debian-sol.yml
  when: (has_grub.stat.exists or has_grub2.stat.exists) and  ansible_os_family == "Debian"
  tags: sol

- name: "Common :: Configure Serial-over-LAN [RedHat]"
  include_tasks: redhat-sol.yml
  when: (has_grub.stat.exists or has_grub2.stat.exists) and  ansible_os_family == "RedHat"
  tags: sol


- name: "Common :: Configure Timezone Info"
  timezone:
    name: "{{ timezone }}"
