---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: configure ssh
  include_tasks: ssh.yml
  tags: ssh

- name: configure sudoers
  include_tasks: sudo.yml
  tags: sudo

- name: install common packages
  package:
    name: "{{ common_pkgs }}"
    state: present
  tags: packages

- name: uninstall python packages
  package:
    name: "{{ common_uninstall_pkgs }}"
    state: absent
  tags: packages

- name: install python packages from pip
  pip:
    name: "{{ common_python_pkgs }}"
    state: present
  tags: packages
  
- name: set up  serial-over-lan
  include_tasks: "{{ ansible_os_family }}-sol.yml"
  tags: sol

- name: set timezone
  timezone:
    name: "{{ timezone }}"
