---
- name: Common :: Load OS-Family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - packages
    - ssh
    - sol
    - sudo

- name: Common :: Install common system packages
  package:
    name: "{{ common_pkgs }}"
    state: present
  tags: packages

- name: Common :: Uninstall any Python requirements currently installed via OS package manager
  package:
    name: "{{ common_uninstall_pkgs }}"
    state: absent
  tags: packages

- name: Common :: Install all Python requirements via Pip
  pip:
    name: "{{ common_python_pkgs }}"
    state: present
  tags: packages

- name: - name: Common :: Configure SSHd and root user
  include_tasks: ssh.yml
  tags: ssh

- name: Common :: Configure Sudoers
  include_tasks: sudo.yml
  tags: sudo

- name: Common :: Configure Serial-over-LAN [Debian]
  include_tasks: debian-sol.yml
  when: ansible_os_family == "Debian" and ansible_lsb.id != "Raspbian"
  tags: sol

- name: Common :: Configure Serial-over-LAN [RedHat]
  include_tasks: redhat-sol.yml
  when: ansible_os_family == "RedHat"
  tags: sol


- name: Common :: Configure Timezone Info
  timezone:
    name: "{{ timezone }}"
