---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Set SELinux State (RHEL)
  when:
    - ansible_os_family == "RedHat"
  failed_when: false
  tags:
    - selinux
  ansible.posix.selinux:
    state: "{{ common_selinux_state }}"


- name: Configure /etc/hosts
  tags:
    - common
  ansible.builtin.include_tasks:
    file: hostfile.yml
    apply:
      tags:
        - hostfile


- name: Configure SSHD
  tags:
    - common
  ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags:
        - sshd

- name: Configure authorized_keys for root user
  tags:
    - common
  ansible.builtin.include_tasks:
    file: root-authorized-keys.yml
    apply:
      tags:
        - root-authorized-keys

- name: Configure Local Users and Groups
  when: not openldap_client_enable | default(false)
  tags:
    - common
  ansible.builtin.include_tasks:
    file: users.yml
    apply:
      tags:
        - users

- name: Configure Sudoers
  tags:
    - common
  ansible.builtin.include_tasks:
    file: sudo.yml
    apply:
      tags:
        - sudoers

- name: Configure Timezone Info
  tags:
    - timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install common system packages and python dependencies for specific OS
  tags:
    - common
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family | lower }}.yml
    apply:
      tags:
        - packages


- name: Install global common pip packages
  tags:
    - common
  ansible.builtin.include_tasks:
    file: packages-pip.yml
    apply:
      tags:
        - pip


- name: Install qemu-guest-agent on KVM hosts
  when:
    - ansible_virtualization_role == "guest"
    - '"kvm" in ansible_virtualization_tech_guest'
  tags:
    - common
  ansible.builtin.include_tasks:
    file: qemu_guest_agent.yml
    apply:
      tags:
        - qemu-guest-agent


- name: Configure Serial-over-LAN
  when:
    - ansible_virtualization_role != "guest"
  tags:
    - common
  ansible.builtin.include_tasks:
    file: grub-config.yml
    apply:
      tags:
        - grub

- name: Configure MDNS reflection / Avahi
  when:
    - common_enable_mdns_reflection | default(False)
  tags:
    - common
  ansible.builtin.include_tasks:
    file: mdns_reflection.yml
    apply:
      tags:
        - mdns

- name: Configure system autoupdate parameters
  tags:
    - common
  ansible.builtin.include_tasks:
    file: autoupdate.yml
    apply:
      tags:
        - autoupdate

- name: Reboot host if grub config was updated
  when: grub_require_rebuild | default(false)
  tags:
    - grub
  ansible.builtin.reboot:
