---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Set SELinux State (RHEL)
  ansible.posix.selinux:
    state: "{{ common_selinux_state }}"
  when:
    - ansible_os_family == "RedHat"
  failed_when: false

- name: Configure SSHD
  ansible.builtin.include_tasks:
    file: ssh.yml
  tags:
    - sshd

- name: Configure authorized_keys for root user
  ansible.builtin.include_tasks:
    file: root-authorized-keys.yml
  tags:
    - root-authorized-keys

- name: Configure Local Users and Groups
  ansible.builtin.include_tasks:
    file: users.yml
  when: not openldap_client_enable | default(false)
  tags:
    - common-users

- name: Configure Sudoers
  ansible.builtin.include_tasks:
    file: sudo.yml
  tags:
    - sudoers

- name: Configure /etc/hosts
  ansible.builtin.include_tasks:
    file: hostfile.yml
  tags:
    - hostfile

- name: Configure Timezone Info
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - timezone

- name: Configure system autoupdate parameters
  ansible.builtin.include_tasks:
    file: autoupdate.yml

  tags:
    - autoupdate

- name: Install common system packages and python dependencies
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family | lower }}.yml
  tags:
    - common-packages

- name: Install common Python packages
  ansible.builtin.include_tasks:
    file: python-packages.yml
  tags:
    - common-python-packages

- name: Install qemu-guest-agent on KVM hosts
  ansible.builtin.include_tasks:
    file: qemu_guest_agent.yml
  when:
    - ansible_virtualization_role == "guest"
    - '"kvm" in ansible_virtualization_tech_guest'
  tags:
    - qemu-guest-agent

- name: Configure Serial-over-LAN
  ansible.builtin.include_tasks:
    file: serial-over-lan.yml
  when:
    - ansible_virtualization_role != "guest"

- name: Configure MDNS reflection / Avahi
  ansible.builtin.include_tasks:
    file: mdns_reflection.yml
  when:
    - enable_mdns_reflection | default(False)
  tags:
    - mdns

- name: Reboot host if grub config was updated
  ansible.builtin.reboot:
  when: grub_require_rebuild | default(false)
  tags:
    - serial-over-lan
