- name: Update all installed packages (RHEL)
  when:
    - ansible_os_family == "RedHat"
  block:

    - name: Install EPEL Repo from upstream URL
      ansible.builtin.yum:
        name:
          - "{{ epel_repo_rpm_url }}"
        disable_gpg_check: true
        update_cache: true
        state: present
      timeout: 600
      retries: 0
      register: epel_setup
      until: epel_setup is not failed

    - name: Update caches and installed packages (RHEL) # noqa package-latest
      ansible.builtin.yum:
        name: "*"
        update_cache: true
        state: latest
        skip_broken: true
      register: yum_update
      until: yum_update is not failed
      timeout: 600
      retries: 0
    - name: Print yum status
      ansible.builtin.debug:
        msg: "{{ yum_update }}"
        verbosity: 1

    - name: Remove unnecessary packages and clean up package database (RHEL) # noqa package-latest
      ansible.builtin.yum:
        autoremove: true
      register: yum_clean
      until: yum_clean is not failed

    - name: Print yum status
      ansible.builtin.debug:
        msg: "{{ yum_clean }}"
        verbosity: 1

- name: Update all installed packages (Debian)
  when:
    - ansible_os_family == "Debian"
  block:

    - name: Update caches and installed packages, clean up package database (Debian) # noqa package-latest
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: true
        upgrade: dist
        state: latest
      register: apt_update
      until: apt_update is not failed
      timeout: 600
      retries: 0

    - name: Print apt upgrade status
      ansible.builtin.debug:
        msg: "{{ apt_update }}"
        verbosity: 1

- name: Install pre-req and common packages, install common python requirements (All Distributions)
  block:
    - name: Install prereq packages
      ansible.builtin.package:
        name: "{{ common_prereq_pkgs }}"
        state: present
      when:
        - common_prereq_pkgs is defined
        - common_prereq_pkgs != None

    - name: Install common packages
      ansible.builtin.package:
        name: '{{ common_pkgs }}'
        state: present
      when:
        - common_pkgs is defined
        - common_pkgs != None

    - name: "Uninstall any unwanted packages managed via OS package-manager"
      ansible.builtin.package:
        name: '{{ common_uninstall_pkgs }}'
        state: absent
      when:
        - common_uninstall_pkgs is defined
        - common_uninstall_pkgs != None

    - name: "Install python requirements via Pip"
      ansible.builtin.pip:
        name: "{{ common_python_pkgs }}"
        state: present
      when:
        - common_python_pkgs is defined
        - common_python_pkgs != None
