---
- name: "Install common system packages"
  package:
    name: "{{ common_pkgs }}"
    state: present

- name: "Uninstall any Python requirements currently installed via OS package manager"
  package:
    name: "{{ common_uninstall_pkgs }}"
    state: absent

- name: "Install all Python2 requirements via Pip"
  pip:
    name: "{{ common_python_pkgs }}"
    state: present
    executable: pip2

- name: "Install all Python3 requirements via Pip"
  pip:
    name: "{{ common_python3_pkgs }}"
    state: present
    executable: pip3