---


- name: packages-debian | DEB Repository and Package Tasks
  tags:
    - os-packages
  block:
    - name: Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml
    - name: packages-debian | Set up Deb822 Apt Repository Source Files and GPG Keys
      ansible.builtin.deb822_repository:
      loop: "{{ common_apt_repos }}"
      args: "{{ item }}"
      register: deb_repo_added
      when:
        - common_apt_repos is defined
        - common_apt_repos | length > 0
      until:
        - deb_repo_added is not failed

    - name: packages-debian | Update APT Repos # noqa no-handler
      ansible.builtin.apt:
        update_cache: true
      register: cache_updated
      until:
        - cache_updated is not failed

    - name: Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml

    - name: packages-debian | Install APT Packages
      ansible.builtin.apt:
        name: "{{ common_apt_pkgs }}"
        state: present
      register: apt_install_result
      until: apt_install_result is not failed
      when:
        - common_apt_pkgs is defined
        - common_apt_pkgs | length > 0

- name: packages-debian | Install {{ common_packages }}
  tags:
    - common-packages
  block:
    - name: Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml

    - name: packages-debian | Install common Packages
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
      register: common_install_result
      until: common_install_result is not failed
      when:
        - common_packages is defined
        - common_packages | length > 0
