---
- name: Install common packages for RedHat
  yum:
    name: "{{ common_pkgs }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install common packages for Ubuntu
  apt:
    name: "{{ common_pkgs }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: "Uninstall any Python requirements currently installed via OS package manager"
  package:
    name: "{{ common_uninstall_pkgs }}"
    state: absent
  when: common_uninstall_pkgs is defined

- name: "Install all Python2 requirements via Pip"
  pip:
    name: "{{ common_python_pkgs }}"
    state: latest
    executable: pip2
  when: common_python_pkgs is defined

- name: "Install all Python3 requirements via Pip"
  pip:
    name: "{{ common_python3_pkgs }}"
    state: latest
    executable: pip3
  when: common_python3_pkgs is defined

#- name: "Set default python to python3"
#  alternatives:
#    name: python
#    path: /usr/bin/python3
#    link: /usr/bin/python
#    priority: -10
