---
- name: packages-debian | DEB Repository and Package Tasks
  tags:
    - packages
  block:
    - name: packages-debian | Set up Deb822 Apt Repository Source Files and GPG Keys
      ansible.builtin.deb822_repository:
      loop: "{{ common_apt_repos }}"
      args: "{{ item }}"
      register: deb_repo_added
      when:
        - common_apt_repos is defined
        - common_apt_repos | length > 0

    - name: packages-debian | Update APT Repos # noqa no-handler
      ansible.builtin.apt:
        update_cache: true
        update_cache_retries: 10
        update_cache_retry_max_delay: 300
        lock_timeout: 300
      register: cache_updated
      until:
        - cache_updated is not failed
      when:
        - deb_repo_added is changed

    - name: packages-debian | Install APT Packages
      ansible.builtin.apt:
        name: "{{ apt_pkgs }}"
        state: "{{ apt_pkgs.state | default('present') }}"
        update_cache: true
      register: apt_install_result
      until: apt_install_result is not failed
      retries: 10
      timeout: 300
      delay: 60
      when:
        - common_apt_pkgs is defined
        - common_apt_pkgs | length > 0
