- name: Install prereq packages
  package:
    name: "{{ common_prereq_pkgs }}"
    state: present
  when:
    - common_prereq_pkgs is defined
    - common_prereq_pkgs != None
- name: Install common packages
  package:
    name: '{{ common_pkgs }}'
    state: present
  when:
    - common_pkgs is defined
    - common_pkgs != None

- name: "Uninstall any unwanted packages managed via OS package-manager"
  package:
    name: '{{ common_uninstall_pkgs }}'
    state: absent
  when:
    - common_uninstall_pkgs is defined
    - common_uninstall_pkgs != None

- name: "Install python requirements via Pip"
  pip:
    name: "{{ common_python_pkgs }}"
    state: present
  when:
    - common_python_pkgs is defined
    - common_python_pkgs != None
