


- name: Check if EPEL repo is already configured
  ansible.builtin.stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result
  when:
    - ansible_os_family == "RedHat"

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: “{{ epel_repo_gpg_key_url }}”
    state: present
  when: 
    - ansible_os_family == "RedHat"
    - not epel_repofile_result.stat.exists


- name: Update all system packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install prereq packages
  package:
    name: "{{ common_prereq_pkgs }}"
    state: present
  when:
    - common_prereq_pkgs is defined
    - common_prereq_pkgs != None

- name: Install common packages
  package:
    name: '{{ common_pkgs }}'
    state: present
  when:
    - common_pkgs is defined
    - common_pkgs != None

- name: "Uninstall any unwanted packages managed via OS package-manager"
  package:
    name: '{{ common_uninstall_pkgs }}'
    state: absent
  when:
    - common_uninstall_pkgs is defined
    - common_uninstall_pkgs != None

- name: "Install python requirements via Pip"
  pip:
    name: "{{ common_python_pkgs }}"
    state: present
  when:
    - common_python_pkgs is defined
    - common_python_pkgs != None
