---
- name: packages-pip | Install pipx
  ansible.builtin.package:
    name: pipx
    state: present


- name: packages-pip | Install python requirements via Pip (All Distributions)
  community.general.pipx:
    name: "{{ item }}"
    state: install
    system_site_packages: true
    install_deps: true
  loop: "{{ query('list', common_pip_pkgs) | default([]) }}"
  when:
    - (common_pip_pkgs | default([]) | length > 0) | default(false)
  register: pip_package_install
  until: pip_package_install is not failed
