---
- name: Install qemu-guest-agent if host is a kvm/qemu virtual machine
  block:
    - name: Install qemu-guest-agent
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present

    - name: Start qemu-guest-agent service
      ansible.builtin.systemd:
        name: qemu-guest-agent
        state: started
        enabled: true
        daemon_reload: true
      register: qemu_guest_agent_startup
      ignore_errors: true

    - name: Assert that qemu-guest-agent is running
      ansible.builtin.assert:
        that: not qemu_guest_agent_startup.failed
        fail_msg: "Fail: qemu-guest-agent failed to start"
        success_msg: "Success: qemu-guest-agent started successfully"
      ignore_errors: true

    - name: Get qemu-guest-agent logs if service failed to start
      ansible.builtin.shell: systemctl status qemu-guest-agent
      register: qemu_guest_agent_status
      when: qemu_guest_agent_startup.failed | default(false)

    - name: Print logs for debugging
      ansible.builtin.debug:
        msg: "{{ qemu_guest_agent_status.stdout_lines }}"
      when: qemu_guest_agent_startup.failed | default(false)
