---
- name: grub linux
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="crashkernel=auto console={{ serialtty }},115200n8,rhgb console={{ consoletty }}"'
  register: update_grub

- name: grub terminal
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_TERMINAL=.*'
    line: 'GRUB_TERMINAL="serial console"'
  register: update_grub

- name: grub serial command
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_SERIAL_COMMAND=.*'
    line: 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=2 --word=8 --parity=no --stop=1"'
  register: update_grub

- name: update grub
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: update_grub.changed
