---
- name: Update GRUB_CMDLINE_LINUX
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="console={{ serialtty }},115200 console={{ consoletty }}"'
  notify: "update_grub_config"

- name: Update GRUB_TERMINAL
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_TERMINAL=.*'
    line: 'GRUB_TERMINAL="serial"'
  notify: "update_grub_config"

- name: Update GRUB_SERIAL_COMMAND
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: '^GRUB_SERIAL_COMMAND=.*'
    line: 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=1 --word=8 --parity=no --stop=1"'
  notify: "update_grub_config"

- name: Rebuild Grub Config
  command: "{{ grub_update_cmd }} -o {{ grub_config }}"
  when: grub_require_rebuild | default(false)
