---
- name: Update /etc/default/grub lines
  tags:
    - serial-over-lan
  block:
    - name: Update Grub lines
      ansible.builtin.lineinfile:
        state: present
      args: "{{ item }}"
      loop: "{{ common_grub_configs }}"
      notify: Update Grub

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Rebuild Grub Config
      ansible.builtin.command: "{{ grub_update_cmd }} -o {{ grub_config }}"
      register: grub_rebuild
      when: grub_require_rebuild | default(false)
      changed_when:
        - grub_rebuild is success

    - name: Copy serial-getty systemd file
      ansible.builtin.copy:
        src: "{{ common_systemd_serial_getty_src }}"
        dest: "{{ common_systemd_serial_getty_dest }}"
        remote_src: true
        group: root
        owner: root
        mode: "0755"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Rebuild Grub Config
  ansible.builtin.command: "{{ grub_update_cmd }} -o {{ grub_config }}"
  register: grub_rebuild
  when: grub_require_rebuild | default(false)
  changed_when:
    - grub_rebuild is defined
