---
- name: Update /etc/default/grub lines
  tags:
    - serial-over-lan
  block:
    - name: Update Grub lines
      ansible.builtin.lineinfile:
        state: present
      args: "{{ item }}"
      loop: "{{ common_grub_configs }}"
      notify: Update Grub

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Rebuild Grub Config
      ansible.builtin.command: "{{ grub_update_cmd }} -o {{ grub_config }}"
      register: grub_rebuild
      when: grub_require_rebuild | default(false)
      changed_when:
        - grub_rebuild is success


- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Rebuild Grub Config
  ansible.builtin.command: "{{ grub_update_cmd }} -o {{ grub_config }}"
  register: grub_rebuild
  when: grub_require_rebuild | default(false)
  changed_when:
    - grub_rebuild is defined

GRUB_TIMEOUT=10
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
GRUB_CMDLINE_LINUX="console=ttyS0,115200 console=tty1 net.ifnames=0 biosdevname=0"
GRUB_TERMINAL="console serial"

cp /lib/systemd/system/serial-getty@.service /etc/systemd/system/serial-getty@ttyS0.service