---

- name: create /var/run/sshd
  file:
    state: directory
    path: /var/run/sshd
    mode: 0755

- name: Copy sshd_config Template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  register: sshd_config_copy

- name: Restart the sshd service
  systemd:
    name: ssh
    state: started
    enabled: yes
  register: ssh_started
  when: sshd_config_copy is changed

- name: Verify the sshd service is listening
  wait_for:
    host: localhost
    port: 22
    delay: 5
  when: ssh_started is changed
  ignore_errors: yes
  register: ssh_start_attempt

- name: Get ssh journald logs if service does not appear to be up
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value ssh.service`
  register: ssh_journal
  when: ssh_start_attempt.failed is defined and ssh_start_attempt.failed == True

- fail:
    msg: "{{ ssh_journal.stdout_lines }}"
  when: ssh_start_attempt.failed is defined and ssh_start_attempt.failed == True


- name: Set root ssh authorized key
  authorized_key:
    user: root
    state: present
    key: "{{ item.value.pubkey }}"
  loop: "{{ ssh_users | dict2items }}"

- name: Change root password
  user:
    name: root
    password: "{{ vault_root_password | password_hash(salt=vault_root_password_salt) }}"
    update_password: always
