---
- name: "Allow passwordless sudo for 'admin' group"
  lineinfile:
    path: /etc/sudoers
    regexp: '^%admin.*$'
    line: '%admin ALL=(ALL) NOPASSWD:ALL'
    state: present
    backup: yes
    validate: 'visudo -cf %s'
