---

- name: passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%wheel.*$'
    line: '%wheel ALL=(ALL) NOPASSWD:ALL'
    state: present
    backup: yes
    validate: 'visudo -cf %s'
  when: ansible_os_family == "RedHat"

- name: passwordless sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%admin.*$'
    line: '%admin ALL=(ALL) NOPASSWD:ALL'
    state: present
    backup: yes
    validate: 'visudo -cf %s'
  when: ansible_os_family == "Debian"

