- name: Create local user groups
  group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid }}"
    state: present
  loop: "{{ ssh_groups | dict2items }}"
  when:
    - ssh_groups is defined
    - ssh_groups != None
- name: Create local user accounts
  user:
    name: "{{ item.key }}"
    shell: "{{ item.value.shell }}"
    group: "{{ item.value.gid }}"
    groups: |
      {% set grouplist = [] %}
      {% for group in ssh_groups | dict2items %}
      {% if item.key in group.value.members %}
      {{ grouplist.append(group.key) }}
      {% endif %}
      {% endfor %}
      {{ grouplist|join(',') }}
    uid: "{{ item.value.uid }}"
    password: "{{ item.value.password | password_hash('sha512', vault_root_password_salt) }}"
  loop: "{{ ssh_users | dict2items }}"
  when:
    - ssh_users is defined
    - ssh_users != None

- name: Add user authorized keys
  authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ item.value.pubkey }}"
  loop: "{{ ssh_users | dict2items }}"
  when:
    - ssh_users is defined
    - ssh_users != None
