---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu-20.04
    box: ubuntu/focal64
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: true
provisioner:
  name: ansible
  options:
    vvv: True
#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
verifier:
  name: ansible
  options:
    vvv: True
  inventory:
    all:
      ceph: []